### ISSUE TITLE
Profile pictures of all contributors are not showing here.

### ISSUE THREAD

**Issue by ahmadsohail404** [ahmadsohail404/Netflix-UI-Clone#24]
<img width="891" alt="Screenshot 2021-10-03 at 2 14 29 PM" src="https://user-images.githubusercontent.com/72069769/135746369-c7b25ac9-2354-4050-b67e-f220c91c91a8.png">

**Comment by alberturria** [comment]
Hi @ahmadsohail404 :man_dancing: Do you mind if I take care of this?

**Comment by ahmadsohail404** [comment]
Go ahead

**Comment by alberturria** [comment]
Hey @ahmadsohail404 I've been diging into the issue and I do not understand why is the `contrib.rocks` page returning just your photo, instead of one with the rest of the 6 contributors.
I've seen that there is an alternative by using [this application](https://github.com/all-contributors/all-contributors). However, in order to automatize the contriburos detection you need to install the `all contributors bot` in your repository.

Let me know if this works for you.

**Comment by ahmadsohail404** [comment]
are you doing this?

**Comment by alberturria** [comment]
I cannot handle the installation of the all-contributors-app since I am not the owner of the repository. This is something that needs to be handled by the owner.

**Comment by ahmadsohail404** [comment]
alright
